### ISSUE TITLE
How is this different than OSS Insights?

### ISSUE THREAD

**Issue by venkatamutyala** [kislerdm/opentofu-stats#1]
Would be nice to know how this is different than https://ossinsight.io/analyze/opentofu/opentofu

Is your app deployed anywhere so that we can view how your calculating/displaying opentofu stats?

**Comment by kislerdm** [comment]
@venkatamutyala Hey! Thanks for sharing the link, it's a great dashboard! May I kindly ask, how did you create it? For context, I didn't know about ossinsight.io 🤷🏻‍♂️ 

An important detail, the dashboard you shared does not seem up to date. The pipeline I set is updated on daily basis, although it could be updated more often.

Moreover, the ossinsight does not contain data about the number of tofu downloads. Also, we would want to provide visibility on the number of providers downloads - find details [here](https://github.com/opentofu/opentofu/issues/258) in the requirements, "strong nice to have" bulletpoint.

The dashboard will be deployed today, so you could compare whether it may be useful 😉

**Comment by venkatamutyala** [comment]
Excited to check it out when it's deployed. And apologies for not grasping the purpose initially but based on your comments and a re-read of the README.md it looks like it'll be a replacement for the stats that the legacy terraform registry usually has displayed alongside their providers.

re: ossinsights. I didn't create it but I wish i did. :) I just searched for your repo and it immediately gives you a dashboard.
